--Track v1 2020-10-13

--Habilitar opción 'Oficinas centrales' para el alta de usuarios
update catalogo.delegaciones set activo = true where clave_delegacional = '09';

update catalogo.elementos_catalogos set descripcion='Podcast', label='Podcast' where id_elemento_catalogo=250;

--Alta de fase de docente de carrera
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(1, 'Fase Inicial', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(2, 'Fase Temprana', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(3, 'Fase Consolidada', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(4, 'Fase Referencial', true);

---Alta de Instituciones
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_buap','BENEMERITA UNIVERSIDAD AUTONOMA DE PUEBLA',56,'',null,true,'BENEMERITA UNIVERSIDAD AUTONOMA DE PUEBLA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_buap-upep','BENEMERITA UNIVERSIDAD AUTONOMA DE PUEBLA/UNIVERSIDAD POPULAR AUTONOMA DEL ESTADO DE PUEBLA',56,'',null,true,'BENEMERITA UNIVERSIDAD AUTONOMA DE PUEBLA/UNIVERSIDAD POPULAR AUTONOMA DEL ESTADO DE PUEBLA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_inspm','INSTITUTO NACIONAL DE SALUD PUBLICA DE MEXICO',56,'',null,true,'INSTITUTO NACIONAL DE SALUD PUBLICA DE MEXICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ipn','INSTITUTO POLITECNICO NACIONAL',56,'',null,true,'INSTITUTO POLITECNICO NACIONAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uabjo','UNIVERSIDAD AUTONOMA BENITO JUAREZ DE OAXACA',56,'',null,true,'UNIVERSIDAD AUTONOMA BENITO JUAREZ DE OAXACA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uaa','UNIVERSIDAD AUTONOMA DE AGUASCALIENTES',56,'',null,true,'UNIVERSIDAD AUTONOMA DE AGUASCALIENTES',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uabc','UNIVERSIDAD AUTONOMA DE BAJA CALIFORNIA',56,'',null,true,'UNIVERSIDAD AUTONOMA DE BAJA CALIFORNIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uacam','UNIVERSIDAD AUTONOMA DE CAMPECHE',56,'',null,true,'UNIVERSIDAD AUTONOMA DE CAMPECHE',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uach','UNIVERSIDAD AUTONOMA DE CHIHUAHUA',56,'',null,true,'UNIVERSIDAD AUTONOMA DE CHIHUAHUA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uacj','UNIVERSIDAD AUTONOMA DE CIUDAD JUAREZ',56,'',null,true,'UNIVERSIDAD AUTONOMA DE CIUDAD JUAREZ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uacoa','UNIVERSIDAD AUTONOMA DE COAHUILA',56,'',null,true,'UNIVERSIDAD AUTONOMA DE COAHUILA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_udg','UNIVERSIDAD AUTONOMA DE GUADALAJARA',56,'',null,true,'UNIVERSIDAD AUTONOMA DE GUADALAJARA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uague','UNIVERSIDAD AUTONOMA DE GUERRERO',56,'',null,true,'UNIVERSIDAD AUTONOMA DE GUERRERO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uana','UNIVERSIDAD AUTONOMA DE NAYARIT',56,'',null,true,'UNIVERSIDAD AUTONOMA DE NAYARIT',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uanl','UNIVERSIDAD AUTONOMA DE NUEVO LEON',56,'',null,true,'UNIVERSIDAD AUTONOMA DE NUEVO LEON',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uaq','UNIVERSIDAD AUTONOMA DE QUERETARO',56,'',null,true,'UNIVERSIDAD AUTONOMA DE QUERETARO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uasl','UNIVERSIDAD AUTONOMA DE SAN LUIS POTOSI',56,'',null,true,'UNIVERSIDAD AUTONOMA DE SAN LUIS POTOSI',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uasi','UNIVERSIDAD AUTONOMA DE SINALOA',56,'',null,true,'UNIVERSIDAD AUTONOMA DE SINALOA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uatam','UNIVERSIDAD AUTONOMA DE TAMAULIPAS',56,'',null,true,'UNIVERSIDAD AUTONOMA DE TAMAULIPAS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uady','UNIVERSIDAD AUTONOMA DE YUCATAN',56,'',null,true,'UNIVERSIDAD AUTONOMA DE YUCATAN',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uaz','UNIVERSIDAD AUTONOMA DE ZACATECAS',56,'',null,true,'UNIVERSIDAD AUTONOMA DE ZACATECAS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uac','UNIVERSIDAD AUTONOMA DEL CARMEN',56,'',null,true,'UNIVERSIDAD AUTONOMA DEL CARMEN',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uaem','UNIVERSIDAD AUTONOMA DEL ESTADO DE MEXICO',56,'',null,true,'UNIVERSIDAD AUTONOMA DEL ESTADO DE MEXICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ucol','UNIVERSIDAD DE COLIMA',56,'',null,true,'UNIVERSIDAD DE COLIMA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ugua','UNIVERSIDAD DE GUADALAJARA',56,'',null,true,'UNIVERSIDAD DE GUADALAJARA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ugua-uguan','UNIVERSIDAD DE GUADALAJARA/UNIVERSIDAD DE GUANAJUATO',56,'',null,true,'UNIVERSIDAD DE GUADALAJARA/UNIVERSIDAD DE GUANAJUATO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uguan','UNIVERSIDAD DE GUANAJUATO',56,'',null,true,'UNIVERSIDAD DE GUANAJUATO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_umon','UNIVERSIDAD DE MONTERREY',56,'',null,true,'UNIVERSIDAD DE MONTERREY',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uqr','UNIVERSIDAD DE QUINTANA ROO',56,'',null,true,'UNIVERSIDAD DE QUINTANA ROO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ujat','UNIVERSIDAD JUAREZ AUTONOMA DE TABASCO',56,'',null,true,'UNIVERSIDAD JUAREZ AUTONOMA DE TABASCO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_ujd','UNIVERSIDAD JUAREZ DEL ESTADO DE DURANGO',56,'',null,true,'UNIVERSIDAD JUAREZ DEL ESTADO DE DURANGO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_umsnh','UNIVERSIDAD MICHOACANA DE SAN NICOLAS DE HIDALGO',56,'',null,true,'UNIVERSIDAD MICHOACANA DE SAN NICOLAS DE HIDALGO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_unam','UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',56,'',null,true,'UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_upap','UNIVERSIDAD POPULAR AUTONOMA DEL ESTADO DE PUEBLA',56,'',null,true,'UNIVERSIDAD POPULAR AUTONOMA DEL ESTADO DE PUEBLA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_uver','UNIVERSIDAD VERACRUZANA',56,'',null,true,'UNIVERSIDAD VERACRUZANA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_fesi-unam','FACULTAD DE ESTUDIOS SUPERIORES DE IZTACALA',56,'',null,true,'FACULTAD DE ESTUDIOS SUPERIORES DE IZTACALA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_conalep','COLEGIO NACIONAL DE EDUCACIÓN PROFESIONAL',56,'',null,true,'COLEGIO NACIONAL DE EDUCACIÓN PROFESIONAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_enba','ESCUELA NACIONAL DE BIBLIOTECONOMÍA Y ARCHIVONOMIA',56,'',null,true,'ESCUELA NACIONAL DE BIBLIOTECONOMÍA Y ARCHIVONOMIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_unadm','UNIVERSIDAD ABIERTA Y A DISTANCIA DE MÉXICO',56,'',null,true,'UNIVERSIDAD ABIERTA Y A DISTANCIA DE MÉXICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_unison','UNIVERSIDAD DE SONORA',56,'',null,true,'UNIVERSIDAD DE SONORA',null,1, true);

--Ya en base final -------
table ui.campos_formulario add column grupo_informacion_campo int DEFAULT 1;

