--Track v1 2020-10-13

--Habilitar opción 'Oficinas centrales' para el alta de usuarios
update catalogo.delegaciones set activo = true where clave_delegacional = '09';

update catalogo.elementos_catalogos set descripcion='Podcast', label='Podcast' where id_elemento_catalogo=250;

--Alta de fase de docente de carrera
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(1, 'Fase Inicial', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(2, 'Fase Temprana', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(3, 'Fase Consolidada', true);
INSERT INTO censo.docente_carrera(id_docente_carrera, descripcion, activo) VALUES(4, 'Fase Referencial', true);

--------------------------Ya en base final ----------------------------
alter table ui.campos_formulario add column grupo_informacion_campo int DEFAULT 1;
alter table censo.docente add column email_personal varchar(255) null;
alter table censo.docente add column ext_tel_laboral int null;


---Alta de Instituciones
delete from catalogo.elementos_catalogos where id_catalogo = 56 and id_elemento_catalogo <> 1775;

INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_1','Ateneo Universitario en Humanidades y Ciencias de la Salud, Campus Tehuacán',56,'',null,true,'Ateneo Universitario en Humanidades y Ciencias de la Salud, Campus Tehuacán',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_2','Benemérita Universidad Autónoma de Puebla',56,'',null,true,'Benemérita Universidad Autónoma de Puebla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_3','Centro de Estudios de Radiología de Durango',56,'',null,true,'Centro de Estudios de Radiología de Durango',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_4','Centro de Estudios Superiores de Guamúchil',56,'',null,true,'Centro de Estudios Superiores de Guamúchil',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_5','Centro de Estudios Superiores de Tepeaca',56,'',null,true,'Centro de Estudios Superiores de Tepeaca',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_6','Centro de Estudios Superiores en Ciencias de la Salud',56,'',null,true,'Centro de Estudios Superiores en Ciencias de la Salud',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_7','Centro de Estudios Superiores en Estomatología y Ciencias de la Salud',56,'',null,true,'Centro de Estudios Superiores en Estomatología y Ciencias de la Salud',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_8','Centro de Estudios Superiores México Americano',56,'',null,true,'Centro de Estudios Superiores México Americano',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_9','Centro de Estudios Universitarios Xochicalco',56,'',null,true,'Centro de Estudios Universitarios Xochicalco',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_10','Centro de Innovación Educativa Roentgen',56,'',null,true,'Centro de Innovación Educativa Roentgen',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_11','Centro Educativo de Humanidades',56,'',null,true,'Centro Educativo de Humanidades',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_12','Centro Universitario Interamericano de Córdoba',56,'',null,true,'Centro Universitario Interamericano de Córdoba',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_13','Centro Universitario UNE',56,'',null,true,'Centro Universitario UNE',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_14','Cruz Roja Mexicana Nuevo León',56,'',null,true,'Cruz Roja Mexicana Nuevo León',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_15','Escuela de Medicina Intermédica',56,'',null,true,'Escuela de Medicina Intermédica',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_16','Escuela de Medicina Saint Luke',56,'',null,true,'Escuela de Medicina Saint Luke',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_17','Escuela de Técnicos en Radiología del Noroeste',56,'',null,true,'Escuela de Técnicos en Radiología del Noroeste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_18','Escuela Superior de Especialidades Educativas y de Artes Chayito Garzon',56,'',null,true,'Escuela Superior de Especialidades Educativas y de Artes Chayito Garzon',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_19','Escuela Superior de Trabajo Social Jesús Aquino Juan - Tapachula',56,'',null,true,'Escuela Superior de Trabajo Social Jesús Aquino Juan - Tapachula',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_20','Instituto Científico de Educación Superior',56,'',null,true,'Instituto Científico de Educación Superior',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_21','Instituto Cultural Tecnológico Cuincacalli',56,'',null,true,'Instituto Cultural Tecnológico Cuincacalli',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_22','Instituto de Ciencias y Estudios Superiores de Tamaulipas',56,'',null,true,'Instituto de Ciencias y Estudios Superiores de Tamaulipas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_23','Instituto de Estudios Superiores Anglo Mexicano de Coatzacoalcos',56,'',null,true,'Instituto de Estudios Superiores Anglo Mexicano de Coatzacoalcos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_24','Instituto de Estudios Superiores de Chiapas Campus Tuxtla',56,'',null,true,'Instituto de Estudios Superiores de Chiapas Campus Tuxtla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_25','Instituto de Estudios Superiores de Chiapas en Tapachula',56,'',null,true,'Instituto de Estudios Superiores de Chiapas en Tapachula',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_26','Instituto de Estudios Superiores del Istmo de Tehuantepec',56,'',null,true,'Instituto de Estudios Superiores del Istmo de Tehuantepec',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_27','Instituto de Estudios Tecnológicos y Superiores Matatipac',56,'',null,true,'Instituto de Estudios Tecnológicos y Superiores Matatipac',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_28','Instituto Dr. Carlos Coqui - Campus Zacatecas',56,'',null,true,'Instituto Dr. Carlos Coqui - Campus Zacatecas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_29','Instituto Dr. Carlos Coqui Campus Coahuila',56,'',null,true,'Instituto Dr. Carlos Coqui Campus Coahuila',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_30','Instituto Educativo Hermosillo',56,'',null,true,'Instituto Educativo Hermosillo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_31','Instituto Hispano Jaime Sabines',56,'',null,true,'Instituto Hispano Jaime Sabines',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_32','Instituto Intercontinental Pierre Fauchard',56,'',null,true,'Instituto Intercontinental Pierre Fauchard',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_33','Instituto Irapuato',56,'',null,true,'Instituto Irapuato',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_34','Instituto Politécnico Nacional',56,'',null,true,'Instituto Politécnico Nacional',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_35','Instituto Regional del Sureste',56,'',null,true,'Instituto Regional del Sureste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_36','Instituto Técnico Superior de Radiología',56,'',null,true,'Instituto Técnico Superior de Radiología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_37','Instituto Tecnológico Superior de Radiología',56,'',null,true,'Instituto Tecnológico Superior de Radiología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_38','Instituto Universitario de Ciencias Médicas y Humanísticas de Nayarit',56,'',null,true,'Instituto Universitario de Ciencias Médicas y Humanísticas de Nayarit',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_39','Instituto Universitario del Sureste',56,'',null,true,'Instituto Universitario del Sureste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_40','Instituto Universitario Franco Inglés de México',56,'',null,true,'Instituto Universitario Franco Inglés de México',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_41','Instituto Universitario Metropolitano Campus Mexicali',56,'',null,true,'Instituto Universitario Metropolitano Campus Mexicali',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_42','Instituto Universitario Metropolitano Campus Tepic',56,'',null,true,'Instituto Universitario Metropolitano Campus Tepic',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_43','Sistema Educativo Universitario Azteca Tuxtla',56,'',null,true,'Sistema Educativo Universitario Azteca Tuxtla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_44','Sistema Educativo Universitario Azteca Tuxtla / Instituto de Estudios Superiores Sor Juana Inés de la Cruz',56,'',null,true,'Sistema Educativo Universitario Azteca Tuxtla / Instituto de Estudios Superiores Sor Juana Inés de la Cruz',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_45','Universidad Americana de Acapulco',56,'',null,true,'Universidad Americana de Acapulco',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_46','Universidad Anáhuac - Mayab',56,'',null,true,'Universidad Anáhuac - Mayab',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_47','Universidad Anáhuac Campus Norte',56,'',null,true,'Universidad Anáhuac Campus Norte',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_48','Universidad Anáhuac Campus Querétaro',56,'',null,true,'Universidad Anáhuac Campus Querétaro',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_49','Universidad Anáhuac Puebla',56,'',null,true,'Universidad Anáhuac Puebla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_50','Universidad Autónoma de Aguascalientes',56,'',null,true,'Universidad Autónoma de Aguascalientes',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_51','Universidad Autónoma de Baja California',56,'',null,true,'Universidad Autónoma de Baja California',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_52','Universidad Autónoma de Campeche',56,'',null,true,'Universidad Autónoma de Campeche',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_53','Universidad Autónoma de Chiapas',56,'',null,true,'Universidad Autónoma de Chiapas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_54','Universidad Autónoma de Chihuahua',56,'',null,true,'Universidad Autónoma de Chihuahua',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_55','Universidad Autónoma de Durango Campus Durango',56,'',null,true,'Universidad Autónoma de Durango Campus Durango',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_56','Universidad Autónoma de Durango Campus Gómez Palacio',56,'',null,true,'Universidad Autónoma de Durango Campus Gómez Palacio',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_57','Universidad Autónoma de Durango Campus Zacatecas',56,'',null,true,'Universidad Autónoma de Durango Campus Zacatecas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_58','Universidad Autónoma de Guadalajara',56,'',null,true,'Universidad Autónoma de Guadalajara',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_59','Universidad Autónoma de Guadalajara - Campus Tabasco',56,'',null,true,'Universidad Autónoma de Guadalajara - Campus Tabasco',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_60','Universidad Autónoma de Nayarit',56,'',null,true,'Universidad Autónoma de Nayarit',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_61','Universidad Autónoma de Nuevo León',56,'',null,true,'Universidad Autónoma de Nuevo León',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_62','Universidad Autónoma de Querétaro',56,'',null,true,'Universidad Autónoma de Querétaro',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_63','Universidad Autónoma de Sinaloa',56,'',null,true,'Universidad Autónoma de Sinaloa',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_64','Universidad Autónoma de Tamaulipas',56,'',null,true,'Universidad Autónoma de Tamaulipas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_65','Universidad Autónoma de Tlaxcala',56,'',null,true,'Universidad Autónoma de Tlaxcala',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_66','Universidad Autónoma de Zacatecas',56,'',null,true,'Universidad Autónoma de Zacatecas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_67','Universidad Autónoma del Carmen',56,'',null,true,'Universidad Autónoma del Carmen',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_68','Universidad Autónoma del Estado de Hidalgo',56,'',null,true,'Universidad Autónoma del Estado de Hidalgo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_69','Universidad Autónoma del Estado de México',56,'',null,true,'Universidad Autónoma del Estado de México',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_70','Universidad Autónoma del Estado de Morelos',56,'',null,true,'Universidad Autónoma del Estado de Morelos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_71','Universidad Autónoma Metropolitana',56,'',null,true,'Universidad Autónoma Metropolitana',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_72','Universidad Centroamericana',56,'',null,true,'Universidad Centroamericana',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_73','Universidad Continente Americano Campus Celaya',56,'',null,true,'Universidad Continente Americano Campus Celaya',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_74','Universidad Cristóbal Colón',56,'',null,true,'Universidad Cristóbal Colón',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_75','Universidad Cuauhtémoc Aguascalientes',56,'',null,true,'Universidad Cuauhtémoc Aguascalientes',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_76','Universidad Cuauhtémoc, Campus Querétaro',56,'',null,true,'Universidad Cuauhtémoc, Campus Querétaro',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_77','Universidad Cuauhtémoc, Campus San Luis Potosí',56,'',null,true,'Universidad Cuauhtémoc, Campus San Luis Potosí',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_78','Universidad de Celaya',56,'',null,true,'Universidad de Celaya',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_79','Universidad de Ciencias de la Enfermería de México',56,'',null,true,'Universidad de Ciencias de la Enfermería de México',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_80','Universidad de Ciencias y Artes de Chiapas',56,'',null,true,'Universidad de Ciencias y Artes de Chiapas',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_81','Universidad de Colima',56,'',null,true,'Universidad de Colima',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_82','Universidad de Durango Campus Chihuahua',56,'',null,true,'Universidad de Durango Campus Chihuahua',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_83','Universidad de Guadalajara',56,'',null,true,'Universidad de Guadalajara',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_84','Universidad de Guadalajara - Centro Universitario de los Altos',56,'',null,true,'Universidad de Guadalajara - Centro Universitario de los Altos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_85','Universidad de Guanajuato',56,'',null,true,'Universidad de Guanajuato',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_86','Universidad de Ixtlahuaca CUI',56,'',null,true,'Universidad de Ixtlahuaca CUI',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_87','Universidad de las Américas Puebla',56,'',null,true,'Universidad de las Américas Puebla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_88','Universidad de Londres',56,'',null,true,'Universidad de Londres',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_89','Universidad de Montemorelos',56,'',null,true,'Universidad de Montemorelos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_90','Universidad de Monterrey',56,'',null,true,'Universidad de Monterrey',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_91','Universidad de Morelia',56,'',null,true,'Universidad de Morelia',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_92','Universidad de Navojoa',56,'',null,true,'Universidad de Navojoa',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_93','Universidad de Sonora',56,'',null,true,'Universidad de Sonora',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_94','Universidad de Sotavento',56,'',null,true,'Universidad de Sotavento',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_95','Universidad de Zamora',56,'',null,true,'Universidad de Zamora',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_96','Universidad del Centro de Veracruz',56,'',null,true,'Universidad del Centro de Veracruz',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_97','Universidad del Noreste',56,'',null,true,'Universidad del Noreste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_98','Universidad del Valle de Atemajac Campus Guadalajara',56,'',null,true,'Universidad del Valle de Atemajac Campus Guadalajara',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_99','Universidad del Valle de México Campus Hermosillo',56,'',null,true,'Universidad del Valle de México Campus Hermosillo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_100','Universidad del Valle de México Campus Veracruz',56,'',null,true,'Universidad del Valle de México Campus Veracruz',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_101','Universidad del Valle de Puebla - Plantel Puebla',56,'',null,true,'Universidad del Valle de Puebla - Plantel Puebla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_102','Universidad del Valle del Fuerte Los Mochis',56,'',null,true,'Universidad del Valle del Fuerte Los Mochis',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_103','Universidad Durango Santander Campus Hermosillo',56,'',null,true,'Universidad Durango Santander Campus Hermosillo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_104','Universidad Guadalupe Victoria',56,'',null,true,'Universidad Guadalupe Victoria',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_105','Universidad Hipócrates',56,'',null,true,'Universidad Hipócrates',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_106','Universidad José Martí',56,'',null,true,'Universidad José Martí',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_107','Universidad Juárez Autónoma de Tabasco',56,'',null,true,'Universidad Juárez Autónoma de Tabasco',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_108','Universidad Juárez del Estado de Durango',56,'',null,true,'Universidad Juárez del Estado de Durango',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_109','Universidad Justo Sierra',56,'',null,true,'Universidad Justo Sierra',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_110','Universidad La Concordia',56,'',null,true,'Universidad La Concordia',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_111','Universidad La Salle, Campus Cancún',56,'',null,true,'Universidad La Salle, Campus Cancún',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_112','Universidad La Salle, Campus Noroeste',56,'',null,true,'Universidad La Salle, Campus Noroeste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_113','Universidad La Salle, Campus Oaxaca',56,'',null,true,'Universidad La Salle, Campus Oaxaca',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_114','Universidad La Salle, Campus San Fernando',56,'',null,true,'Universidad La Salle, Campus San Fernando',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_115','Universidad Latina de América',56,'',null,true,'Universidad Latina de América',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_116','Universidad Latina de México Celaya',56,'',null,true,'Universidad Latina de México Celaya',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_117','Universidad Latinoamericana Campus Cuernavaca',56,'',null,true,'Universidad Latinoamericana Campus Cuernavaca',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_118','Universidad Marista de Mérida',56,'',null,true,'Universidad Marista de Mérida',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_119','Universidad Marista de Valladolid',56,'',null,true,'Universidad Marista de Valladolid',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_120','Universidad Metropolitana de Tlaxcala',56,'',null,true,'Universidad Metropolitana de Tlaxcala',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_121','Universidad Modelo',56,'',null,true,'Universidad Modelo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_122','Universidad Mundial',56,'',null,true,'Universidad Mundial',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_123','Universidad Nacional Autónoma de México',56,'',null,true,'Universidad Nacional Autónoma de México',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_124','Universidad Pablo Guardado Chávez',56,'',null,true,'Universidad Pablo Guardado Chávez',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_125','Universidad Panamericana',56,'',null,true,'Universidad Panamericana',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_126','Universidad para la Profesionalización Estratégica',56,'',null,true,'Universidad para la Profesionalización Estratégica',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_127','Universidad Popular Autónoma del Estado de Puebla',56,'',null,true,'Universidad Popular Autónoma del Estado de Puebla',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_128','Universidad Popular de la Chontalpa',56,'',null,true,'Universidad Popular de la Chontalpa',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_129','Universidad Quetzalcoatl Irapuato',56,'',null,true,'Universidad Quetzalcoatl Irapuato',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_130','Universidad Regional del Sureste',56,'',null,true,'Universidad Regional del Sureste',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_131','Universidad Rosaritense',56,'',null,true,'Universidad Rosaritense',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_132','Universidad Tecnológica de México / UNITEC',56,'',null,true,'Universidad Tecnológica de México / UNITEC',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_133','Universidad Teletón',56,'',null,true,'Universidad Teletón',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_134','Universidad Univer Milenium',56,'',null,true,'Universidad Univer Milenium',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_135','Universidad Vasco de Quiroga',56,'',null,true,'Universidad Vasco de Quiroga',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_136','Universidad Veracruzana',56,'',null,true,'Universidad Veracruzana',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('inst_edu_137','Universidad Westhill',56,'',null,true,'Universidad Westhill',null,1, true);

--Alta de tipo de profesores
delete from catalogo.elementos_catalogos where id_catalogo = 62;

INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_1','N41 - Coordinador de cursos de enfermería',62,1,null,true,'N41 - Coordinador de cursos de enfermería',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_2','N41 - Coordinador de cursos técnicos',62,1,null,true,'N41 - Coordinador de cursos técnicos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_3','Profesor titular de servicio social',62,1,null,true,'Profesor titular de servicio social',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_4','Profesor adjunto de servicio social',62,1,null,true,'Profesor adjunto de servicio social',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_5','Profesor titular de asignatura',62,1,null,true,'Profesor titular de asignatura',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_6','Profesor adjunto de asignatura',62,1,null,true,'Profesor adjunto de asignatura',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_7','Profesor asociado de asignatura',62,1,null,true,'Profesor asociado de asignatura',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_8','Tutor de campo clínico',62,1,null,true,'Tutor de campo clínico',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_9','Profesor titular',62,1,null,true,'Profesor titular',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_10','Profesor adjunto',62,1,null,true,'Profesor adjunto',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_11','Instructor de practica clínica',62,1,null,true,'Instructor de practica clínica',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_12','Profesor ayudante',62,1,null,true,'Profesor ayudante',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_13','Tutor titular',62,1,null,true,'Tutor titular',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_14','Coordinador de tutores',62,1,null,true,'Coordinador de tutores',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_prof_15','Coordinador de curso',62,1,null,true,'Coordinador de curso',null,1, true);

--Alta de tipo de cursos
delete from catalogo.elementos_catalogos where id_catalogo = 15 and id_elemento_catalogo <> 208;
update catalogo.elementos_catalogos set activo = false where id_elemento_catalogo=208;

INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_1','Posgrado',15,null,null,true,'Posgrado',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_2','Pregrado',15,null,null,true,'Pregrado',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_3','Enfermería y técnicos',15,null,null,true,'Enfermería y técnicos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_4','Educación continua (Adiestramientos institucional/ extrainstitucional)',15,null,null,true,'Educación continua (Adiestramientos institucional/ extrainstitucional)',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_5','Educación a Distancia',15,null,null,true,'Educación a Distancia',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('tipo_curso_6','CIEFD',15,null,null,true,'CIEFD',null,1, true);


--Alta de cursos
delete from catalogo.elementos_catalogos where id_catalogo = 61 and id_elemento_catalogo = 1797;

INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_1','CPE-SALUD MENTAL',61,1,null,true,'CPE-SALUD MENTAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_2','CPE-CUIDADOS INTENSIVOS',61,1,null,true,'CPE-CUIDADOS INTENSIVOS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_3','CPE-GERIATRIA',61,1,null,true,'CPE-GERIATRIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_4','CPE-GESTIÓN MF',61,1,null,true,'CPE-GESTIÓN MF',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_5','CPE-GESTIÓN 2DO Y 3ER',61,1,null,true,'CPE-GESTIÓN 2DO Y 3ER',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_6','CPE-MEDICINA DE FAMILIA',61,1,null,true,'CPE-MEDICINA DE FAMILIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_7','CPE-NEFROLOGÍA',61,1,null,true,'CPE-NEFROLOGÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_8','CPE-ONCOLOGÍA',61,1,null,true,'CPE-ONCOLOGÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_9','CPE-PEDIATRÍA',61,1,null,true,'CPE-PEDIATRÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_10','CPE-QUIRURGICA',61,1,null,true,'CPE-QUIRURGICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_11','CPE-SALUD PÚBLICA',61,1,null,true,'CPE-SALUD PÚBLICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_12','GESTIÓN Y EDUCACIÓN EN NUTRICIÓN CLÍNICA ESPECIALIZADA',61,1,null,true,'GESTIÓN Y EDUCACIÓN EN NUTRICIÓN CLÍNICA ESPECIALIZADA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_13','NUTRIOLOGO CLINICO ESPECIALIZADO',61,1,null,true,'NUTRIOLOGO CLINICO ESPECIALIZADO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_14','TEMAE-TÉCNICO EN EL MANEJO DE APARATOS PARA ELECTRODIAGNÓSTICO',61,1,null,true,'TEMAE-TÉCNICO EN EL MANEJO DE APARATOS PARA ELECTRODIAGNÓSTICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_15','AUX LABORATORIO',61,1,null,true,'AUX LABORATORIO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_16','AUX TECNICO EN ENFERMERÍA',61,1,null,true,'AUX TECNICO EN ENFERMERÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_17','HISTOTECNÓLOGO',61,1,null,true,'HISTOTECNÓLOGO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_18','CITOTECNÓLOGO EN HOSPITAL RURAL',61,1,null,true,'CITOTECNÓLOGO EN HOSPITAL RURAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_19','CITOTECNÓLOGO  INTEGRAL',61,1,null,true,'CITOTECNÓLOGO  INTEGRAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_20','CURSO NIVELATORIO DE RADIOTERAPIA',61,1,null,true,'CURSO NIVELATORIO DE RADIOTERAPIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_21','CITOTECNÓLOGO EN DIVERSOS',61,1,null,true,'CITOTECNÓLOGO EN DIVERSOS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_22','TÉCNICO EN MEDICINA NUCLEAR',61,1,null,true,'TÉCNICO EN MEDICINA NUCLEAR',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_23','TÉCNICO DE BIBLIOTECAS',61,1,null,true,'TÉCNICO DE BIBLIOTECAS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_24','PTB RADIOTERAPEUTA',61,1,null,true,'PTB RADIOTERAPEUTA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_25','PTB TERAPIA FÍSICA',61,1,null,true,'PTB TERAPIA FÍSICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_26','PTB TERAPIA OCUPACIONAL',61,1,null,true,'PTB TERAPIA OCUPACIONAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_27','PTB FONOAUDIÓLOGO',61,1,null,true,'PTB FONOAUDIÓLOGO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_28','PTB ASISTENTE DE BIBLIOTECARIO',61,1,null,true,'PTB ASISTENTE DE BIBLIOTECARIO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_29','PTB NUTRICIONISTA DIETISTA',61,1,null,true,'PTB NUTRICIONISTA DIETISTA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_30','PTB TERAPIA RESPIRATORIA',61,1,null,true,'PTB TERAPIA RESPIRATORIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_31','PTB RADIOLOGÍA E IMAGEN',61,1,null,true,'PTB RADIOLOGÍA E IMAGEN',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_32','PTB LABORATORISTA CLÍNICO',61,1,null,true,'PTB LABORATORISTA CLÍNICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_33','PTB ENFERMERÍA GENERAL',61,1,null,true,'PTB ENFERMERÍA GENERAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_34','LICENCIATURA EN ENFERMERÍA',61,1,null,true,'LICENCIATURA EN ENFERMERÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_35','LICENCIATURA EN ENFERMERÍA (NO ESCOLARIZADA)',61,1,null,true,'LICENCIATURA EN ENFERMERÍA (NO ESCOLARIZADA)',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_36','PROFESIONAL TÉCNICO ASOCIADO EN BIBLIOTECONOMIA',61,1,null,true,'PROFESIONAL TÉCNICO ASOCIADO EN BIBLIOTECONOMIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_37','LICENCIATURA EN NUTRICIÓN APLICADA',61,1,null,true,'LICENCIATURA EN NUTRICIÓN APLICADA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_38','SERVICIO SOCIAL DE ENFERMERÍA',61,1,null,true,'SERVICIO SOCIAL DE ENFERMERÍA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_39','PRÁCTICAS CLINICAS DE ENFERMERÍA ',61,1,null,true,'PRÁCTICAS CLINICAS DE ENFERMERÍA ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_40','Cirujano dentista',61,1,null,true,'Cirujano dentista',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_41','Dental',61,1,null,true,'Dental',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_42','Enfermería',61,1,null,true,'Enfermería',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_43','Estomatología',61,1,null,true,'Estomatología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_44','Farmacia',61,1,null,true,'Farmacia',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_45','Fisioterapia',61,1,null,true,'Fisioterapia',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_46','Gerontología',61,1,null,true,'Gerontología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_47','Medicina',61,1,null,true,'Medicina',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_48','Nutrición',61,1,null,true,'Nutrición',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_49','Odontología',61,1,null,true,'Odontología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_50','Optometría',61,1,null,true,'Optometría',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_51','Profesional técnico bachiller en terapia respiratoria',61,1,null,true,'Profesional técnico bachiller en terapia respiratoria',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_52','Profesional técnico nutricionista dietista',61,1,null,true,'Profesional técnico nutricionista dietista',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_53','Psicología',61,1,null,true,'Psicología',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_54','Químico biólogo parasitólogo',61,1,null,true,'Químico biólogo parasitólogo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_55','Químico clínico',61,1,null,true,'Químico clínico',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_56','Químico fármaco biólogo',61,1,null,true,'Químico fármaco biólogo',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_57','Radiología e imagen',61,1,null,true,'Radiología e imagen',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_58','Rehabilitación',61,1,null,true,'Rehabilitación',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_59','Salud pública',61,1,null,true,'Salud pública',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_60','Trabajo social ',61,1,null,true,'Trabajo social ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_61','Terapia física',61,1,null,true,'Terapia física',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_62','Terapia ocupacional',61,1,null,true,'Terapia ocupacional',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_63','ALERGIA E INMUNOLOGIA CLINICA',61,1,null,true,'ALERGIA E INMUNOLOGIA CLINICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_64','ALERGIA E INMUNOLOGIA CLINICA PEDIATRICA',61,1,null,true,'ALERGIA E INMUNOLOGIA CLINICA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_65','ANATOMIA PATOLOGICA',61,1,null,true,'ANATOMIA PATOLOGICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_66','ANESTESIOLOGIA',61,1,null,true,'ANESTESIOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_67','ANESTESIOLOGIA PARA LOS SERVICIOS RURALES DE SALUD',61,1,null,true,'ANESTESIOLOGIA PARA LOS SERVICIOS RURALES DE SALUD',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_68','ANESTESIOLOGIA PEDIATRICA',61,1,null,true,'ANESTESIOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_69','ANGIOLOGIA Y CIRUGIA VASCULAR',61,1,null,true,'ANGIOLOGIA Y CIRUGIA VASCULAR',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_70','BIOLOGIA DE LA REPRODUCCION HUMANA',61,1,null,true,'BIOLOGIA DE LA REPRODUCCION HUMANA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_71','CALIDAD DE LA ATENCION CLINICA',61,1,null,true,'CALIDAD DE LA ATENCION CLINICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_72','CARDIOLOGIA',61,1,null,true,'CARDIOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_73','CARDIOLOGIA PEDIATRICA',61,1,null,true,'CARDIOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_74','CIRUGIA CARDIOTORACICA',61,1,null,true,'CIRUGIA CARDIOTORACICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_75','CIRUGIA GENERAL',61,1,null,true,'CIRUGIA GENERAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_76','CIRUGIA MAXILOFACIAL',61,1,null,true,'CIRUGIA MAXILOFACIAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_77','CIRUGIA ONCOLOGICA',61,1,null,true,'CIRUGIA ONCOLOGICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_78','CIRUGIA PARA LOS SERVICIOS RURALES DE SALUD',61,1,null,true,'CIRUGIA PARA LOS SERVICIOS RURALES DE SALUD',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_79','CIRUGIA PEDIATRICA',61,1,null,true,'CIRUGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_80','CIRUGIA PLASTICA Y RECONSTRUCTIVA',61,1,null,true,'CIRUGIA PLASTICA Y RECONSTRUCTIVA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_81','COLOPROCTOLOGIA',61,1,null,true,'COLOPROCTOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_82','COMUNICACION - AUDIOLOGIA Y FONIATRIA',61,1,null,true,'COMUNICACION - AUDIOLOGIA Y FONIATRIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_83','DERMATOLOGIA',61,1,null,true,'DERMATOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_84','ENDOCRINOLOGIA',61,1,null,true,'ENDOCRINOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_85','ENDOCRINOLOGIA PEDIATRICA',61,1,null,true,'ENDOCRINOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_86','EPIDEMIOLOGIA',61,1,null,true,'EPIDEMIOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_87','GASTROENTEROLOGIA',61,1,null,true,'GASTROENTEROLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_88','GASTROENTEROLOGIA Y NUTRICION PEDIATRICA ',61,1,null,true,'GASTROENTEROLOGIA Y NUTRICION PEDIATRICA ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_89','GENETICA MEDICA',61,1,null,true,'GENETICA MEDICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_90','GERIATRIA ',61,1,null,true,'GERIATRIA ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_91','GINECOLOGIA ONCOLOGICA',61,1,null,true,'GINECOLOGIA ONCOLOGICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_92','GINECOLOGIA Y OBSTETRICIA',61,1,null,true,'GINECOLOGIA Y OBSTETRICIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_93','HEMATOLOGIA',61,1,null,true,'HEMATOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_94','HEMATOLOGIA PEDIATRICA',61,1,null,true,'HEMATOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_95','IMAGENOLOGIA DIAGNOSTICA Y TERAPEUTICA',61,1,null,true,'IMAGENOLOGIA DIAGNOSTICA Y TERAPEUTICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_96','INFECTOLOGIA',61,1,null,true,'INFECTOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_97','INFECTOLOGIA PEDIATRICA',61,1,null,true,'INFECTOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_98','MEDICINA DE REHABILITACION',61,1,null,true,'MEDICINA DE REHABILITACION',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_99','MEDICINA DEL ENFERMO EN ESTADO CRITICO',61,1,null,true,'MEDICINA DEL ENFERMO EN ESTADO CRITICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_100','MEDICINA DEL ENFERMO PEDIATRICO EN ESTADO CRITICO',61,1,null,true,'MEDICINA DEL ENFERMO PEDIATRICO EN ESTADO CRITICO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_101','MEDICINA DEL NIÑO Y DEL ADULTO PARA LOS SERVICIOS RURALES DE SALUD',61,1,null,true,'MEDICINA DEL NIÑO Y DEL ADULTO PARA LOS SERVICIOS RURALES DE SALUD',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_102','MEDICINA DEL TRABAJO',61,1,null,true,'MEDICINA DEL TRABAJO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_103','MEDICINA FAMILIAR',61,1,null,true,'MEDICINA FAMILIAR',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_104','MEDICINA INTERNA',61,1,null,true,'MEDICINA INTERNA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_105','MEDICINA MATERNO FETAL',61,1,null,true,'MEDICINA MATERNO FETAL',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_106','MEDICINA NUCLEAR',61,1,null,true,'MEDICINA NUCLEAR',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_107','MEDICINA PALIATIVA',61,1,null,true,'MEDICINA PALIATIVA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_108','NEFROLOGIA',61,1,null,true,'NEFROLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_109','NEFROLOGIA PEDIATRICA',61,1,null,true,'NEFROLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_110','NEONATOLOGIA',61,1,null,true,'NEONATOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_111','NEUMOLOGIA ',61,1,null,true,'NEUMOLOGIA ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_112','NEUMOLOGIA PEDIATRICA',61,1,null,true,'NEUMOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_113','NEUROCIRUGIA',61,1,null,true,'NEUROCIRUGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_114','NEUROCIRUGIA PEDIATRICA',61,1,null,true,'NEUROCIRUGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_115','NEUROFISIOLOGIA CLINICA',61,1,null,true,'NEUROFISIOLOGIA CLINICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_116','NEUROLOGIA',61,1,null,true,'NEUROLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_117','NEUROLOGIA PEDIATRICA',61,1,null,true,'NEUROLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_118','OFTALMOLOGIA',61,1,null,true,'OFTALMOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_119','ONCOLOGIA MEDICA',61,1,null,true,'ONCOLOGIA MEDICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_120','ONCOLOGIA PEDIATRICA',61,1,null,true,'ONCOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_121','ORTOPEDIA',61,1,null,true,'ORTOPEDIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_122','OTORRINOLARINGOLOGIA PEDIATRICA',61,1,null,true,'OTORRINOLARINGOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_123','OTORRINOLARINGOLOGIA Y CIRUGIA DE CABEZA Y CUELLO',61,1,null,true,'OTORRINOLARINGOLOGIA Y CIRUGIA DE CABEZA Y CUELLO',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_124','PATOLOGIA CLINICA',61,1,null,true,'PATOLOGIA CLINICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_125','PATOLOGIA PEDIATRICA',61,1,null,true,'PATOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_126','PEDIATRIA',61,1,null,true,'PEDIATRIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_127','PSIQUIATRIA',61,1,null,true,'PSIQUIATRIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_128','PSIQUIATRIA INFANTIL Y DE LA ADOLESCENCIA',61,1,null,true,'PSIQUIATRIA INFANTIL Y DE LA ADOLESCENCIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_129','RADIONCOLOGIA ',61,1,null,true,'RADIONCOLOGIA ',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_130','REUMATOLOGIA',61,1,null,true,'REUMATOLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_131','REUMATOLOGIA PEDIATRICA',61,1,null,true,'REUMATOLOGIA PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_132','URGENCIAS MEDICO QUIRURGICAS',61,1,null,true,'URGENCIAS MEDICO QUIRURGICAS',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_133','URGENCIAS PEDIATRICA',61,1,null,true,'URGENCIAS PEDIATRICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_134','UROLOGIA',61,1,null,true,'UROLOGIA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_135','UROLOGIA GINECOLOGICA',61,1,null,true,'UROLOGIA GINECOLOGICA',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_136','Diplomados de Profesionalización docente',61,1,null,true,'Diplomados de Profesionalización docente',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_137','Diplomados de Directivos Médicos',61,1,null,true,'Diplomados de Directivos Médicos',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_138','Diplomados de Enferemería',61,1,null,true,'Diplomados de Enferemería',null,1, true);
INSERT INTO catalogo.elementos_catalogos(nombre, descripcion, id_catalogo, tipo, id_catalogo_elemento_padre, activo, "label", orden, nivel, is_validado) VALUES('curso_curso_139','Estrategia en salud Mental',61,1,null,true,'Estrategia en salud Mental',null,1, true);


--Definición de sede académica 
update catalogo.unidades_instituto set sede_academica=false;
update catalogo.unidades_instituto set sede_academica=true where id_tipo_unidad is not null and anio=2020;
update catalogo.unidades_instituto set sede_academica=true where anio=2020 and (clave_unidad like '__UC%' or clave_unidad like '__UJ%' or clave_unidad like '__UM%' or clave_unidad like '__UN%' or clave_unidad like '__UL%');


--   n uevos
CREATE TABLE "sistema"."control_registro_usuarios" (

"id_usuario_registra" int4 NOT NULL,

"id_usuario_registrado" int4 NOT NULL,

"active" bool DEFAULT true,

PRIMARY KEY ("id_usuario_registra", "id_usuario_registrado")

);

ALTER TABLE "sistema"."control_registro_usuarios" ADD CONSTRAINT "pk_usuario_registra" FOREIGN KEY ("id_usuario_registra") REFERENCES "sistema"."usuarios" ("id_usuario");

ALTER TABLE "sistema"."control_registro_usuarios" ADD CONSTRAINT "pk_usuario_registrado" FOREIGN KEY ("id_usuario_registrado") REFERENCES "sistema"."usuarios" ("id_usuario");

